// The Meridian — public fields from Notion (Publish Status = Published), 3 Oct 2026.
// In production this is generated at build time from the Notion API.
(function () {
  const CAT = { B: 'Books & Literature', S: 'Scientific Instruments', N: 'Navigation & Cartography', O: 'Optics & Photography', W: 'Writing & Correspondence' };
  // slug, name, year, date label, era, origin, verification, kind (book|box|folio), category, flags (f=featured, i=The Island), short description
  const R = [
    ["aw-faber-castell-360-slide-rule-1927","A.W. Faber Castell 360 Slide Rule",1930,"c.1927–1934","Interwar","Germany","V","box","S","","Before calculators, this is how the world did its maths. A celluloid-faced pearwood Mannheim slide rule by A.W. Faber \"Castell\", made in Bavaria c.1927–1934 for the English-speaking export market, with patented anti-warp bracing and its original glass cursor."],
    ["hermes-media-portable-typewriter-1939","Hermes Media Portable Typewriter",1939,"c.1939–1945","Interwar","Switzerland","V","box","W","f","A Swiss precision portable built in wartime (c.1939–1945) by Paillard of Yverdon, with a rare professional fraction keyboard, its original case and instruction booklet, and the label of a London dealer founded in 1884."],
    ["shortland-brothers-wall-barometer-1947","Shortland Brothers Wall Barometer & Thermometer",1947,"1947","Mid-Century","England","V","box","S","","An Art Deco oak weather station with a patented dual-hand forecasting dial, presented by a Cornish football club to one of its own on 22 November 1947, name and date still polished into the brass."],
    ["ensign-ful-vue-super-1954","Ensign Ful-Vue Super Camera",1954,"c.1954","Mid-Century","England","V","box","O","","The camera that taught Britain to look down, not through: a 1954 Ross Ensign pseudo-TLR with a glowing waist-level finder, one shutter speed, and a lineage reaching back to Daguerre's London licence of 1839."],
    ["descrittione-isola-taprobana-1590","Descrittione dell'Isola Taprobana",1590,"c.1590","Renaissance","Italy","V","folio","N","fi","A Venetian copperplate map of an island Europe argued over for two thousand years: Taprobana, the dream-version of Sri Lanka, engraved by Girolamo Porro for Porcacchi's island atlas, c.1590."],
    ["england-south-1948","England South",1948,"1948","Mid-Century","England","V","book","B","","Forty years of sketch-books opened in the year England needed them most: the first volume of Sydney R. Jones's illustrated journey through the southern counties, from London to the very end of Cornwall (1948)."],
    ["england-west-1950","England West",1950,"1950","Mid-Century","England","V","book","B","","The trilogy's longest journey: Thames to Hadrian's Wall through Cotswold wool churches, Shakespeare country, the Marches, and the industrial North. The richest of the three volumes in architectural range (1950)."],
    ["england-east-1954","England East",1954,"1954","Mid-Century","England","V","book","B","","The farewell volume: Jones closes his life's work with a journey from the Thames to the Scottish border, saluting Durham coalminers alongside Northumbrian castles, under an epigraph about ashes and graves (1954)."],
    ["gleam-in-the-north-1930","The Gleam in the North",1930,"1930 impression","Interwar","England","V","book","B","","A novel that keeps a promise: its final scenes use the actual last words of Dr Archibald Cameron, the last Jacobite executed for treason. Heinemann, 1930 impression, the trilogy's fifth printing in three years."],
    ["great-white-chief-1908","The Great White Chief",1908,"1908","Edwardian","England","V","book","B","","'The characters are real, and the incidents not imaginary': an Edwardian New Guinea adventure that reads like a prospector's disguised memoir, with eight Rainey plates, a folding map, and a Christmas 1918 inscription."],
    ["flight-of-the-heron-1927","The Flight of the Heron",1927,"1927","Interwar","England","V","book","B","","The defining Jacobite novel of the 20th century, built on a heron prophecy and an impossible friendship across enemy lines; this copy from the 1927 cheaper edition, inscribed by its first owner, Dickie Mackenzie."],
    ["wounded-name-1929","The Wounded Name",1929,"1929","Interwar","England","V","book","B","","Dedicated 'to friendship' and titled from Hamlet's dying words: Broster's 1815-set novel of a hero falsely disgraced, here in two Heinemann impressions (1926–27 and 1928–29) from the Windmill Press."],
    ["natures-arts-and-crafts-1910s","Nature's Arts and Crafts",1918,"c.1917–1920s","Edwardian","England","R","book","B","","Spiders as architects, squirrels as bankers, bower birds as upholsterers: an Edwardian nature book for children, awarded as an LCC school prize to Osmond Hollington of Tooting for English, July 1937."],
    ["pietas-quotidiana-1826","Pietas Quotidiana: Prayers & Meditations",1830,"c.1826–1840","Georgian","England","R","book","B","f","A Georgian pocket prayer book with no title on its spine and a deathbed angel for a frontispiece: daily piety in navy leather and gilt, London c.1826–1840, with a prayer by a guillotined French princess inside."],
    ["works-of-william-shakspeare-1879","The Works of William Shakspeare",1890,"c.1879–1900","Victorian","England","R","book","B","","The complete Shakespeare, spelled 'Shakspeare' defiantly, squeezed onto 921 india-paper pages for ordinary Victorian households. One of 340,000 copies that put the national poet in the parlour (Warne, c.1879–1900)."],
    ["war-and-peace-1943","War and Peace",1943,"1943","Mid-Century","England","V","book","B","","Tolstoy's epic of the 1812 invasion, printed in Britain in 1943, while history repeated itself outside Moscow. The Tolstoy-endorsed Maude translation on wartime paper, with the invasion fold-out map intact."],
    ["the-idiot-1968","The Idiot",1968,"1968","Mid-Century","England","V","book","B","","Dostoevsky's experiment in dropping a genuinely good man into society: the 1968 Heron Books gilt-and-leatherette edition, ribbon bookmark intact, spine spelled 'DOSTOEVSKI'."],
    ["brothers-karamazov-vol-1-1968","The Brothers Karamazov, Vol. I",1968,"1968","Mid-Century","England","V","book","B","","The first half of what Freud called 'the most magnificent novel ever written': Garnett's pioneering translation in the 1968 Heron gilt edition, containing the Grand Inquisitor, with an old £1.25 pencil price as a fossil of its travels."],
    ["brothers-karamazov-vol-2-1968","The Brothers Karamazov, Vol. II",1968,"1968","Mid-Century","England","V","book","B","","The trial, the devil, and Dostoevsky's last written word of hope: the concluding volume of his final masterpiece in the 1968 Heron gilt edition, completing the set with Volume I."],
    ["album-von-bremen-1891","Album von Bremen",1891,"1891","Victorian","Germany","V","folio","O","","Twelve egg-white photographs of a city the bombs later erased: an 1891 concertina-fold souvenir of Hanseatic Bremen, including monuments that became UNESCO World Heritage 113 years after the shutter clicked."],
    ["lady-agnes-and-other-poems-1878","Lady Agnes and Other Poems",1878,"1878","Victorian","England","V","book","B","","Thirty-one poems by a man history declined to remember: the first and only edition of an unknown Manchester poet's lifework, 1878, with a preface that fires one perfect shot at literary fashion."],
    ["sacred-bo-tree-anuradhapura-1885","Sacred Bo Tree, Anuradhapura",1885,"c.1875–1895","Victorian","Sri Lanka (Ceylon)","V","folio","O","fi","A Scowen & Co. albumen view of the terraced steps to the Sacred Bo Tree at Anuradhapura — the oldest human-planted tree on earth with a recorded planting date."],
    ["poems-lord-byron-1904","Poems by Lord Byron",1906,"c.1904–1906","Edwardian","England","V","book","B","","Byron in Art Nouveau gilt, introduced by the critic who brought Symbolism to England, signed in pencil by Cecile Mary Davies two days before Valentine's Day, 1906. Price: one shilling and sixpence."],
    ["thuparama-dagoba-dalada-maligawa-1885","Thuparama Dagoba & Dalada Maligawa, Anuradhapura",1885,"c.1875–1895","Victorian","Sri Lanka (Ceylon)","V","folio","O","fi","Scowen & Co.'s albumen view of Thuparama — the first stupa built in Sri Lanka — ringed by the leaning pillars of its ancient relic-house and a lost Temple of the Tooth."],
    ["view-from-serendip-1979","The View from Serendip",1979,"1979","Late 20th C.","United Kingdom","R","book","B","i","Clarke's Sri Lankan essays in the 1979 Pan paperback, inscribed by him at Colombo in 1980 to a 'Professor Shoenberg' — most likely the Cambridge physicist David Shoenberg."],
    ["fifty-amazing-stories-great-war-1936","Fifty Amazing Stories of the Great War",1936,"1936","Interwar","England","V","book","B","","One of Odhams' vast 1936 omnibus volumes: fifty first-hand stories of the First World War told largely by men who fought it, in flexible gilt-stamped covers."],
    ["fifty-true-stories-stranger-than-fiction-1936","Fifty True Stories Stranger Than Fiction",1936,"1936","Interwar","England","V","book","B","","A 1936 Odhams omnibus of fifty 'stranger than fiction' true tales, with contributors ranging from Winston Churchill and Rider Haggard to a Foreign Legion novelist."],
    ["fifty-thrilling-wild-west-stories-odhams-1938","Fifty Thrilling Wild West Stories",1938,"c.1938","Interwar","England","V","book","B","","Fifty pulp Westerns bound as one fat Odhams omnibus (c.1938) — Max Brand, the creator of Hopalong Cassidy, the creator of Zorro, and even O. Henry between gilt covers."],
    ["poetical-works-robert-bridges-1914","Poetical Works of Robert Bridges",1914,"1914","Edwardian","England","V","book","B","","The 1914 Oxford Edition of the Poet Laureate's verse, gift-inscribed 'To Dear Alice' at Christmas 1920, with two 1936 literary clippings — on Bridges, and on the Gielgud–Ashcroft 'Seagull' — laid inside."],
    ["canterbury-tales-1952","The Canterbury Tales",1952,"1952","Mid-Century","England","V","book","B","","Nevill Coghill's landmark modern-verse Canterbury Tales — Penguin Classics L22, the 1952 reprint of the 1951 translation that later became a West End musical — signed by an owner, 'Marion Sills'."],
    ["flags-of-the-world-1928","Flags of the World, Past and Present",1928,"1928","Interwar","England","V","book","N","","Frederick Warne's richly illustrated flag book in its 1928 revised-supplement printing — the world's banners just after Versailles redrew the map — signed by an owner in 1929."],
    ["short-history-of-england-1917","A Short History of England",1917,"1917","Edwardian","England","V","book","B","","G. K. Chesterton's contrarian 1917 first-edition history of England — a defence of the medieval common man against the Whigs — once owned by a 'Francesca Claremont', possibly the Tudor biographer."],
    ["abbeys-castles-ancient-halls-north-wales-1905","Abbeys, Castles and Ancient Halls of England & Wales: North & Wales",1905,"early 20th c.","Edwardian","England","V","book","B","","Volume III (North & Wales) of Timbs's Victorian gazetteer of castle-and-abbey legend, revised by Alexander Gunn — a Frederick Warne reprint, Caerphilly Castle as frontispiece."],
    ["character-smiles-1874","Character",1874,"1874","Victorian","England","V","book","B","","Samuel Smiles's 'Character' (1874 New Edition, John Murray) — the sequel to 'Self-Help' and a cornerstone of the Victorian self-improvement gospel — with a woman's ownership signature."],
    ["preface-to-shakespeare-1925","A Preface to Shakespeare",1925,"1925","Interwar","England","V","book","B","","A 1925 first-edition Shakespeare primer by George H. Cowling — written at Leeds in the years he worked alongside Tolkien — bearing the bookplate of a 'James Craigie, M.A.'"],
    ["songs-of-grace-and-glory-1872","Songs of Grace and Glory",1872,"1872","Victorian","England","V","book","B","","An 1872 Victorian evangelical hymnal of 1,025 hymns, edited by Charles Snepp with music by the famous hymnwriter Frances Ridley Havergal — signed 'Mary Hawes 1874'."],
    ["song-tide-1888","Song-Tide",1888,"1888","Victorian","England","V","book","B","","An 1888 shilling selection of 'the Blind Poet' Philip Bourke Marston — friend of Rossetti and Swinburne — edited with a memoir by William Sharp, later the secret 'Fiona Macleod'."],
    ["lingards-history-england-vol-1-1855","Lingard's History of England, Vol. I",1855,"1855","Victorian","England","V","book","B","","Volume I of Lingard's Catholic history of England — Roman Britain to 1100, the span he knew best, centred on the conversion of the English."],
    ["lingards-history-england-vol-2-1855","Lingard's History of England, Vol. II",1855,"1854–55","Victorian","England","V","book","B","","Volume II of Lingard's history — Henry I to Edward I: Becket, Magna Carta and the first parliaments, told without the Whig gloss."],
    ["lingards-history-england-vol-3-1855","Lingard's History of England, Vol. III",1855,"1854–55","Victorian","England","V","book","B","","Volume III of Lingard's history — the fourteenth century: Crécy, Agincourt, the Black Death, and the first fuse toward the Reformation in Wycliffe."],
    ["lingards-history-england-vol-4-1855","Lingard's History of England, Vol. IV",1855,"1854–55","Victorian","England","V","book","B","","Volume IV of Lingard's history — Wars of the Roses to the eve of the break with Rome: the structural pivot of the whole work."],
    ["lingards-history-england-vol-5-1855","Lingard's History of England, Vol. V",1855,"1854–55","Victorian","England","V","book","B","","Volume V of Lingard's history — the Reformation head-on: the break with Rome, the dissolution of the monasteries, and the see-saw of Henry, Edward and Mary."],
    ["lingards-history-england-vol-6-1855","Lingard's History of England, Vol. VI",1855,"1854–55","Victorian","England","V","book","B","","Volume VI of Lingard's history — 'Good Queen Bess' from the other side: Elizabeth's reign told from the standpoint of the Catholics it persecuted."],
    ["lingards-history-england-vol-7-1855","Lingard's History of England, Vol. VII",1855,"1854–55","Victorian","England","V","book","B","","Volume VII of Lingard's history — the early Stuarts to the brink of civil war, including his measured verdict on the Gunpowder Plot."],
    ["lingards-history-england-vol-8-1855","Lingard's History of England, Vol. VIII",1855,"1854–55","Victorian","England","V","book","B","","Volume VIII of Lingard's history — the Civil War, the regicide and Cromwell's republic, narrated by a Catholic priest with conspicuous restraint."],
    ["lingards-history-england-vol-10-1855","Lingard's History of England, Vol. X",1855,"1854–55","Victorian","England","V","book","B","","Volume X, the last of Lingard's history — the fall of England's last Catholic king and the 1688 revolution the Whigs called Glorious."],
    ["agfa-synchro-box-1951","Agfa Synchro-Box",1951,"1951–1957","Mid-Century","Germany","V","box","O","","A German 1950s box camera, complete with its multilingual manual — and found still loaded with an exposed, undeveloped roll of Fuji Provia slide film, a ~20-year-old mystery awaiting the lab."],
    ["coronet-ambassador-1955","Coronet Ambassador",1955,"c.1955","Mid-Century","England","V","box","O","","A British 1950s box camera by Coronet of Birmingham — 6×9 on 120 film, with Coro-Flash sync — complete, fully working, and with its original instruction booklet."],
    ["french-pictures-pen-and-pencil-1878","French Pictures, Drawn with Pen and Pencil",1878,"1878","Victorian","England","V","book","B","","A Victorian RTS gift-book of pen-and-pencil views of France by Samuel G. Green — this copy layered with a French family's marks: 'Marcelle Dubois, Kent', a gift from 'Mamoyke', and a child's hand-drawn title page."],
    ["italian-pictures-pen-and-pencil-1880s","Italian Pictures, Drawn with Pen and Pencil",1878,"c.1880s","Victorian","England","V","book","B","","The companion to the collection's French Pictures — an RTS 'Pen and Pencil' gift-book of wood-engraved Italy (Rome, Pompeii, Florence, Venice), begun by Samuel Manning and revised by S. G. Green; pencil owner's initials 'DH'."],
    ["immortal-gilbert-sullivan-operas-vol-3-1932","The Immortal Gilbert & Sullivan Operas, Vol. 3",1932,"c.1932","Interwar","England","V","book","B","","Volume 3 of the News Chronicle's 1930s illustrated Gilbert & Sullivan part-work — the 'odd volume' pairing Trial by Jury and the flop Grand Duke with Patience and Ruddigore — endorsed by the last great D'Oyly Carte comedian, Sir Henry Lytton."],
    ["popular-history-great-war-vol-4-1933","A Popular History of the Great War, Vol. IV",1933,"1933","Interwar","England","V","book","B","","Volume IV (1917) of Sir J. A. Hammerton's mass-market 1933 Great War history from the Amalgamated Press — the year of Passchendaele, Vimy, Caporetto, the American entry and the Russian Revolution."],
    ["popular-history-great-war-vol-3-1933","A Popular History of the Great War, Vol. III",1933,"1933","Interwar","England","V","book","B","","Volume III (1916) of Sir J. A. Hammerton's mass-market 1933 Great War history from the Amalgamated Press — the year of Verdun, the Somme, Jutland, the Easter Rising and the coming of the tank."],
    ["popular-history-great-war-vol-1-1933","A Popular History of the Great War, Vol. I",1933,"1933","Interwar","England","V","book","B","","Volume I (1914) of Sir J. A. Hammerton's mass-market 1933 Great War history — the opening year: the outbreak, the invasion of Belgium, Mons, the Marne, Tannenberg and First Ypres."],
    ["popular-history-great-war-vol-2-1933","A Popular History of the Great War, Vol. II",1933,"1933","Interwar","England","V","book","B","","Volume II (1915) of Sir J. A. Hammerton's mass-market 1933 Great War history — the year the war spread: Gallipoli, Second Ypres and first gas, the Lusitania, Loos and the U-boat."]
  ];
  const MAKERS = {
    "aw-faber-castell-360-slide-rule-1927": "A.W. Faber \"Castell\", Stein, Bavaria, Germany",
    "hermes-media-portable-typewriter-1939": "Paillard S.A., Yverdon-les-Bains, Switzerland",
    "shortland-brothers-wall-barometer-1947": "Shortland Brothers (later Shortland Smiths), England",
    "ensign-ful-vue-super-1954": "Ross Ensign Ltd., London, England",
    "descrittione-isola-taprobana-1590": "Tomaso Porcacchi (author); Girolamo Porro (engraver); Venice, Italy",
    "pietas-quotidiana-1826": "Printed by W. Willcocks, London; published by Peacock & Mansfield, Bowdery & Kerby, and Charles Tilt, Fleet Street",
    "sacred-bo-tree-anuradhapura-1885": "Scowen & Co. (Charles T. Scowen), Kandy & Colombo, Ceylon",
    "thuparama-dagoba-dalada-maligawa-1885": "Scowen & Co. (Charles T. Scowen), Kandy & Colombo, Ceylon",
    "flight-of-the-heron-1927": "D. K. Broster (author); William Heinemann Ltd, London",
    "natures-arts-and-crafts-1910s": "W. J. Claxton (author); P. J. Billinghurst (illustrator); Wells Gardner, Darton & Co. Ltd., London",
    "album-von-bremen-1891": "Ernst Roepke, Wiesbaden, Germany",
    "agfa-synchro-box-1951": "Agfa Camera-Werk AG, Munich, Germany"
  };
  const items = R.map((r, i) => ({
    slug: r[0], name: r[1], year: r[2], date: r[3], era: r[4], origin: r[5],
    verified: r[6] === 'V', verification: r[6] === 'V' ? 'Verified' : 'Research Ongoing',
    kind: r[7], category: CAT[r[8]], featured: r[9].includes('f'), island: r[9].includes('i'),
    short: r[10], maker: MAKERS[r[0]] || '', order: i
  }));
  const narratives = [
    { slug: 'picturing-place', name: 'Picturing Place: Four Centuries of Looking', premise: 'From an engraved guess at Taprobana to albumen prints of Bremen to pen-and-ink England: three technologies for taking a place home.', items: ['descrittione-isola-taprobana-1590','album-von-bremen-1891','england-south-1948','england-west-1950','england-east-1954'] },
    { slug: 'england-trilogy-jones', name: 'The England Trilogy, Complete', premise: "Sydney R. Jones's three-volume pen-and-ink survey of England, complete: South (1948), West (1950), East (1954).", items: ['england-south-1948','england-west-1950','england-east-1954'] },
    { slug: 'broster-jacobite-shelf', name: 'The Broster Shelf: Jacobites Between the Wars', premise: 'Three interwar Heinemann hardbacks of D. K. Broster: novels of honourable defeat, read by the generation that survived the trenches.', items: ['flight-of-the-heron-1927','wounded-name-1929','gleam-in-the-north-1930'] },
    { slug: 'russia-in-translation', name: 'Russia in Translation', premise: 'Four volumes, three translators: how Tolstoy and Dostoevsky crossed into English, from wartime reprint to mail-order classics.', items: ['war-and-peace-1943','the-idiot-1968','brothers-karamazov-vol-1-1968','brothers-karamazov-vol-2-1968'] },
    { slug: 'analogue-toolkit', name: 'The Analogue Toolkit', premise: 'Calculate, write, forecast, see: four machines of the pre-electronic everyday, each one now an app on a phone.', items: ['aw-faber-castell-360-slide-rule-1927','hermes-media-portable-typewriter-1939','shortland-brothers-wall-barometer-1947','ensign-ful-vue-super-1954'] },
    { slug: 'other-peoples-hands', name: "Other People's Hands", premise: 'Inscriptions, prize labels, plaques and stamps: seven objects whose previous owners left their names behind.', items: ['lady-agnes-and-other-poems-1878','poems-lord-byron-1904','great-white-chief-1908','natures-arts-and-crafts-1910s','flight-of-the-heron-1927','war-and-peace-1943','shortland-brothers-wall-barometer-1947'] },
    { slug: 'two-christmases', name: 'Two Christmases', premise: 'Two books given at Christmas, 1918 and 1927. Gift inscriptions as time stamps on what a decade hoped for.', items: ['great-white-chief-1908','flight-of-the-heron-1927'] },
    { slug: 'camera-and-album', name: 'The Camera and the Album', premise: 'Bremen 1891 and England 1954: from buying photographs made by professionals to taking your own.', items: ['album-von-bremen-1891','ensign-ful-vue-super-1954'] },
    { slug: 'pocket-gilt', name: 'Pocket Gilt: Books Made to Be Carried', premise: 'A Georgian prayer book and an Edwardian pocket Byron, eighty years apart, solving the same problem: beauty that fits in a pocket.', items: ['pietas-quotidiana-1826','poems-lord-byron-1904'] },
    { slug: 'literature-for-the-parlour', name: 'Literature for the Parlour', premise: 'How the masterpiece came down off the luxury shelf and into ordinary front rooms: Shakespeare by the third of a million, a pocket Byron, mail-order Dostoevsky, and one poet nobody bought.', items: ['lady-agnes-and-other-poems-1878','works-of-william-shakspeare-1879','poems-lord-byron-1904','the-idiot-1968','brothers-karamazov-vol-1-1968','brothers-karamazov-vol-2-1968'] },
    { slug: 'the-year-1927', name: 'The Year 1927', premise: "One year surfaces three times across the shelf: a school prize in July, a Christmas inscription, and a slide rule's production run.", items: ['natures-arts-and-crafts-1910s','flight-of-the-heron-1927','aw-faber-castell-360-slide-rule-1927'], year: 1927 },
    { slug: 'books-in-wartime', name: 'Books in Wartime', premise: 'A 1918 gift inscription, a Swiss typewriter built 1939–1945, and War and Peace reprinted in 1943: war as it appears in margins, dates, and paper.', items: ['great-white-chief-1908','hermes-media-portable-typewriter-1939','war-and-peace-1943'] }
  ];
  const bySlug = {};
  items.forEach(it => { bySlug[it.slug] = it; it.narratives = []; });
  narratives.forEach(n => n.items.forEach(s => bySlug[s] && bySlug[s].narratives.push(n.slug)));
  window.MERIDIAN_DATA = { items, narratives, bySlug };
})();
